# Generated by Django 5.2.9 on 2025-12-24 11:15

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(choices=[('Tr', 'Traveling'), ('ASq', 'Art Seq'), ('DSSq', 'Dance Step Seq'), ('FoSq', 'Foot Seq'), ('ClSq', 'Cluster Sequence'), ('1SClSq', 'One Set Cluster Seq'), ('ChStS', 'Choreo Step Seq'), ('IF2', 'Italian Foxtrot Section 2'), ('SWT1', 'Sweet Tango'), ('TW1', 'Terenzi Waltz Section 1')], max_length=50, null=True)),
                ('level', models.IntegerField(choices=[(0, 'No level'), (1, 'Base'), (2, '1'), (3, '2'), (4, '3'), (5, '4')], default=0)),
                ('base_score', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('extra_points', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
            ],
            options={
                'verbose_name': 'Element',
                'verbose_name_plural': 'Elements',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('is_program', models.BooleanField(default=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='skating.element')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Skater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('free_elements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='List of element codes/names for Free program', size=None)),
                ('style_elements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='List of element codes/names for Style program', size=None)),
                ('elements', models.ManyToManyField(blank=True, related_name='skaters', through='skating.Result', to='skating.element')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='result',
            name='skater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='skating.skater'),
        ),
    ]
