# Generated by Django 5.2.9 on 2025-12-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
