# Generated by Django 5.2.9 on 2025-12-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skating', '0003_skater_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='qoe_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='element',
            name='qoe_2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='element',
            name='qoe_3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='element',
            name='base_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='element',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
