# Generated by Django 5.2.9 on 2025-12-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skating', '0005_result_qoe_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(choices=[('Tr', 'Traveling'), ('ASq', 'Art Seq'), ('DSSq', 'Dance Step Seq'), ('FoSq', 'Foot Seq'), ('ClSq', 'Cluster Sequence'), ('1SClSq', 'One Set Cluster Seq'), ('ChStS', 'Choreo Step Seq'), ('IF2', 'Italian Foxtrot Section 2'), ('SWT1', 'Sweet Tango'), ('TW1', 'Terenzi Waltz Section 1'), ('QSS1', 'Quickstep Sequence 1')], max_length=50, null=True),
        ),
    ]
